package Datos;
// Generated 25-10-2015 09:16:15 AM by Hibernate Tools 3.2.1.GA

import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;




/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int ci;
     private String nombre;
  HibernateUtil hibernate = new HibernateUtil();
    
    Session conexion;
    
    public Persona() {
            conexion=hibernate.getSessionFactory().openSession();
    }

	
    public Persona(int ci) {
        this.ci = ci;
    }
    public Persona(int ci, String nombre) {
       this.ci = ci;
       this.nombre = nombre;
           conexion=hibernate.getSessionFactory().openSession();
    }
   
    public int getCi() {
        return this.ci;
    }
    
    public void setCi(int ci) {
        this.ci = ci;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

 public Persona insertar(){
  
     conexion= hibernate.getSessionFactory().openSession();
     Transaction tra= conexion.beginTransaction();
    try {
      
        conexion.save(this);
       //tra.commit();
        conexion.flush();
       return this; 
    } catch (HibernateException e) {
    }
  return null;
 }

 public Persona buscar(int id) {
        Persona t = (Persona) conexion.createCriteria(Persona.class).add(Restrictions.eq("ci", id)).uniqueResult();
        return t;
    }
 
// public static void main(String []As){
//      
// }
 
}


